baseURL = 'https://kaushikbhat.com/'
languageCode = 'en-us'
title = 'Kaushik Bhat'
theme = 'anubis2'

[author]
name = "Kaushik"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[params]
readMore = false # true | false; Showing readmore link in the list of posts; default: false
readNextPosts = 3 # Number of posts to show in the "Read Next" section; default: 3
colorTheme = "auto" # "auto" | "light" | "dark"; default: "auto"
colorThemeSwitcher = true # true | false; Showing color theme switcher in top of the site; default: false
toc = false # true | false; Showing table of contents in the post; default: true
math = false # true | false; Enable MathJax; default: false; You can enable MathJax in the post by adding math: true in a post's metadata section.

# check more social icons at https://github.com/Junyi-99/hugo-theme-anubis2/wiki/Social-Icons
social = [
     { id="twitter", name="kaushikb9" },
     { id="linkedin", url="https://www.linkedin.com/in/kaushikbhat/" },
     { id="github", name="kaushikb9" },

]


[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

# [markup.highlight]
# style = 'base16-snazzy' # Highlight.js style

